#!/bin/bash
set -eu
cd "$(dirname "$0")"

# get env
source .env || :

# parse args
DAY="${1:-$DAY}"
PART="${2:-${PART:-1}}"

# misc vars
PADDED_DAY="$(printf "%02d" "$DAY")"
FILE="$YEAR/day$PADDED_DAY-P$PART.py"
INPUT=".inputs/cache$YEAR-day$PADDED_DAY.txt"

# setup
mkdir -p .inputs

# lint, get inputs, and run code
uv tool run pylint "$FILE"
[ -f "$INPUT" ] || curl -f --cookie session="$SESSION" "https://adventofcode.com/$YEAR/day/$DAY/input" -o "$INPUT"
uv run "$FILE" <"$INPUT"

